[package]
name = "icon-cache"
version = "0.1.0"
edition = "2024"

[features]
alloc = ["zerocopy/alloc"]

[dependencies]
derive_more = { version = "2.0.1", features = ["debug"] }
memmap2 = "0.9.5"
zerocopy = { version = "0.8.25", features = ["derive"] }
